### ISSUE TITLE
Decide how to handle the AccountDelete transaction fee

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl.js#1117]
The `AccountDelete` Transaction has a transaction cost of 5,000,000 drops (before load scaling), per https://xrpl.org/transaction-cost.html#special-transaction-costs

This bumps into the 2,000,000 drop fee limit imposed on all transactions by default, so `AccountDelete` can't be used unless `maxFeeXRP` is set to '5' or higher. https://xrpl.org/rippleapi-reference.html

Is this acceptable, or do we want to make a special case for `AccountDelete`?

**Comment by ximinez** [comment]
My feeling is that deleting an account is unusual enough, both in expected frequency and in having the much higher fee, that I don't see a problem requiring callers to set `maxFeeXRP` for that case. If they choose to set `maxFeeXRP` for all transactions, they're only going over the default by 2.5x so it's not an enormous mistake.

**Comment by tuloski** [comment]
I agree with @ximinez .

**Comment by intelliot** [comment]
👍 We'll just need to make sure this requirement is well-documented so folks aren't confused when their AccountDelete tx fails due to setting the fee too low.

**Comment by mvadari** [comment]
Resolved by #1626
