### ISSUE TITLE
Transaction events leads to uncomplete information

### ISSUE THREAD

**Issue by AGallouin** [XRPLF/xrpl.js#1304]
Hello !

When you subscribe to a transaction stream in order to maintain an orderbook in real time using https://xrpl.org/rippleapi-reference.html#listening-to-streams, it seems I'm missing something in term of data consistency.
Let me explain myself:
I'm maintaining an orderbook listening to the transactions stream. I'm listening to the initial snapshot and then applying every new final transaction to a local copy of the orderbook in order to keep it up to date in the most efficient way possible.
The problem is that I want to publish the final orderbook for each ledger as soon as it is valid, but it's not that easy.
The transaction event is fired once / transaction, so, in a new ledger, I may have n transaction events. But I don't know how many. I want to publish the updated book as soon as possible, but I may have another transaction following that will change it.

Ie:
- Snaphot ledger n
- First transaction event ledger n + 1 => If I want to publish the book ASAP, I would be tempted to publishing it here, but the information is imcomplete, because the 2nd transaction isn't applied yet.
- Second transaction event ledger n + 1 => I need to publish the book just after that, but I don't know if there is many others comming

This is particulary annoying especially when dealing with market makers bot that usually cancel a transaction to republish it with different specs in the same ledger: at one instant, a book can be published with twice the actual liquidity (one order to be cancelled + the order with the new specs) or none (all orders cancelled).

Right now, the best option I've seen is just to wait if there is more transaction event comming, if not publishing the book, but, as you guessed it, it's quite a delay killed.
This problem would be easily solved if instead of a transaction, the server could give a transaction[] for the ledger. The array would be applied atomically, and the book published without any delay.

Is there a way to solve that problem in an elegant manner ? Have I missed a transaction count somewhere ?

Thanks for your insights,

**Comment by sublimator** [comment]
You can subscribe to the ledger event.
The header includes the transaction count if I recall correctly ?

**Comment by mvadari** [comment]
The best way to do this is probably to subscribe to the `ledger` event, and submit a `ledger` request with `transactions: true` every time you receive an event. That will give you a `transactions[]` for the ledger. The `ledger` event also gives you a `txn_count`, so you could also use that in concert with your current system.

If you think this should be changed, then you should open up an issue on the rippled repo: https://github.com/ripple/rippled/

**Comment by intelliot** [comment]
It has been a while, so I'll close this issue due to inactivity. @AGallouin feel free to reach out again if the issue persists.
