### ISSUE TITLE
Check conditions prior AccountDelete call

### ISSUE THREAD

**Issue by cujo30227** [XRPLF/xrpl.js#1406]
One of the conditions for AccountDelete to succeed, is that the account must not be linked to any of the following types of ledger objects (as a sender or receiver): Escrow, PayChannel, RippleState, Check.

Is there an easy call to check this prior to executing a submit action? When the submit action fails because of non-eligibility, there is still 5 XRP deducted..

Thanks!

**Comment by yxxyun** [comment]
{
"id": 1,
"command": "account_objects",
"account": "r........",
"ledger_index": "validated",
"deletion_blockers_only": "true"
}

**Comment by intelliot** [comment]
In addition to account_objects deletion_blockers_only, I believe you can use submit_hard when submitting the AccountDelete transaction. This should prevent the tecHAS_OBLIGATIONS from being validated (which would deduct the 5 XRP fee).

**Comment by ximinez** [comment]
@intelliot I think you're thinking of `fail_hard`.

**Comment by mvadari** [comment]
Resolved by #1626
