### ISSUE TITLE
Test cases fail intermittently

### ISSUE THREAD

**Issue by khancode** [XRPLF/xrpl.js#1488]
There are a few test cases that fail intermittently; it takes around 15 `yarn test` attempts to get them to fail on my machine.

The common error that is shown with these test cases failing is `Uncaught Error: listen EADDRINUSE: address already in use :::49155`. However, the test case and port number are always different each time it fails.

Investigating the root cause, I found an error is thrown trying to establish a mock connection inside `function setupMockRippledConnection(testcase, port)`
This is the error message inside its catch block: 
```
NotConnectedError: WebSocket was closed before the connection was established
at WebSocket.Connection._onConnectionFailed (/Users/okhan/Development/ripple/ripple-lib/src/common/connection.ts:2:14456)
at WebSocket.emit (events.js:387:35)
at WebSocket.emit (domain.js:470:12)
at abortHandshake (/Users/okhan/Development/ripple/ripple-lib/node_modules/ws/lib/websocket.js:868:15)
at WebSocket.close (/Users/okhan/Development/ripple/ripple-lib/node_modules/ws/lib/websocket.js:269:14)
at /Users/okhan/Development/ripple/ripple-lib/src/common/connection.ts:2:22880
at new Promise (<anonymous>)
```

I tried including retry logic but it would still fail with the same error for each retry attempt.

**Comment by mvadari** [comment]
I suspect `getFreePort` also needs to be investigated

**Comment by mvadari** [comment]
This issue still exists, but the testing structure has been rewritten enough that when it occurs, it only crashes a section of the tests instead of all the tests. Also, it seems to happen way less frequently now. That's good enough for us for now.
