### ISSUE TITLE
Make it easier for developers to find the GitHub repo + code

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl.js#1539]
Common landing pages:

https://xrpl.org/get-started-using-node-js.html

https://xrpl.org/rippleapi-reference.html

-> We should have prominent links to the GitHub repo so that people can check out the code and contribute to the evolution of the library

**Comment by Ayushsunny** [comment]
Hey @intelliot Can i work on this?

**Comment by mvadari** [comment]
This should be an issue on xrpl-dev-portal

**Comment by intelliot** [comment]
@Ayushsunny Yes. Go ahead and fork https://github.com/XRPLF/xrpl-dev-portal and open a PR there.

**Comment by Ayushsunny** [comment]
Hey @intelliot , So I have to add this repo links on the pages you referenced above or on every page?

**Comment by intelliot** [comment]
Just the pages referenced above.

**Comment by saurav2799** [comment]
Is there a developer docs / reference page for NFT transactions ?

**Comment by JST5000** [comment]
> Is there a developer docs / reference page for NFT transactions ?

Here's the latest proposal for having NFT's on the ledger along with discussion of it: https://github.com/XRPLF/XRPL-Standards/discussions/46

**Comment by JST5000** [comment]
This appears to be done :)
