### ISSUE TITLE
Ripple public node S1, S2: Unable to verify the first certificate

### ISSUE THREAD

**Issue by anhcao142** [XRPLF/xrpl.js#1711]
Hi, today I randomly encounter this error `request to https://s2.ripple.com:51234/ failed, reason: unable to verify the first certificate`. This happens when I try to access through RPC calls e.g. 

```bash
curl -L -X POST 'https://s2.ripple.com:51234/' -H 'Content-Type: application/json' --data-raw '{
    "method": "ledger",
    "params": [
        {
            "ledger_index": "validated"
        }
    ]
}'
```

I've tried this [answer](https://stackoverflow.com/a/60020493/1766225) to download the intermediate certificate and include it when starting my server but the error still persists.

**Comment by cjcobb23** [comment]
s2.ripple.com should be back now

**Comment by natenichols** [comment]
Closing since it sounds like this was resolved.
