### ISSUE TITLE
Using lib in browser throwing errors.

### ISSUE THREAD

**Issue by shortthefomo** [XRPLF/xrpl.js#1763]
References to "process" are exposed and are throwing errors when using this lib in a front end like vue.
<img width="1841" alt="Screen Shot 2021-10-20 at 21 44 31" src="https://user-images.githubusercontent.com/508629/138191695-afb150d0-f6ba-4934-8289-589fc483f326.png">

specifically its looking for process.env.NODE_DEBUG in utilis.js in the lib

**Comment by lathanbritz** [comment]
here is the package.json and the view in vue im adding the lib.

<img width="667" alt="Screen Shot 2021-10-21 at 09 46 53" src="https://user-images.githubusercontent.com/508629/138280436-80feea9e-5d5d-48e3-b56c-b394b6fe9f7c.png">
<img width="333" alt="Screen Shot 2021-10-21 at 09 47 07" src="https://user-images.githubusercontent.com/508629/138280443-e8f4f658-abfa-4ccc-bb6e-8c12c736c117.png">

**Comment by natenichols** [comment]
This looks like it might be an issue with polyfilling in vite: https://github.com/vitejs/vite/issues/728

What do y'all think?
