### ISSUE TITLE
Escrow example using crypto conditions 

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/xrpl.js#1766]
Can we get a code snippet using escrows and a cryptographic condition(s) https://datatracker.ietf.org/doc/html/draft-thomas-crypto-conditions-04

not a timer but rather the condition used as the gate to release the tx.

**Comment by mvadari** [comment]
I don't see a snippet in the xrpl.js docs, but there is a tutorial: https://xrpl.org/create-conditional-escrows-using-javascript.html

**Comment by JST5000** [comment]
The snippet on xrpl.org fills this need now.
