### ISSUE TITLE
Same Sequence Problem 

### ISSUE THREAD

**Issue by junha-ahn** [XRPLF/xrpl.js#1792]
### rippled node version 1.7.3

Hi, I have some problem with "XRP sending"

I think It's not a bug or something, It might be my mistake. so plz tell me some tips to do

```javascript
async function multiSignPayment(paymentObject) {
  const { from, to, amount, tag } = paymentObject
  const defaultFees = 30
  const recommendedFees = (await rippleAPI.getFee()) * 1e6
  const multiSignPayment = {
    TransactionType: 'Payment',
    Account: from,
    Destination: to,
    Amount: amount,
    Fee: Math.min(Math.max(recommendedFees, defaultFees), 420000).toString() // 0.00003 XRP max: 0.42 XRP
  }

  // Force the TX to fail after 25 blocks instead of 3 (slow connections / IO /...)
  const instructions = {
    maxLedgerVersionOffset: 25
  }

  if (tag) multiSignPayment.DestinationTag = Number(tag)

  const prepared = await rippleAPI.prepareTransaction(
    multiSignPayment,
    instructions
  )

  // * Get Account & Secrets
  const signers = await Secrets.getSigners()
  const signedTransactions = signers.map(({ address, account, secret }) => {
    const addr = address || account
    return rippleAPI.sign(prepared.txJSON, secret, { signAs: addr })
      .signedTransaction
  })
  const combinedTx = rippleAPI.combine(signedTransactions)

  const result = await rippleAPI.submit(combinedTx.signedTransaction)
  const ledger = await rippleAPI.getLedger()

  console.log(result) // my log point

  return { result, ledger }
}
```

```
2021-11-10T00:53:51.829Z {"resultCode":"telINSUF_FEE_P","Fee":"532","LastLedgerSequence":67598148,"Sequence":xxx,"hash":"...."}
2021-11-10T00:53:54.979Z {"resultCode":"telINSUF_FEE_P","Fee":"1039","LastLedgerSequence":67598149,"Sequence":xxx,"hash":"..."}
2021-11-10T00:54:18.262Z {"resultCode":"telINSUF_FEE_P","Fee":"30421","LastLedgerSequence":67598156,"Sequence":xxx,"hash":"..."}
2021-11-10T00:54:21.410Z {"resultCode":"telINSUF_FEE_P","Fee":"16042","LastLedgerSequence":67598157,"Sequence":xxx,"hash":"..."}
2021-11-10T00:56:14.362Z {"resultCode":"telINSUF_FEE_P","Fee":"420000","LastLedgerSequence":67598184,"Sequence":xxx,"hash":"..."}
2021-11-10T01:01:17.263Z {"resultCode":"telINSUF_FEE_P","Fee":"420000","LastLedgerSequence":67598260,"Sequence":xxx,"hash":"..."}
2021-11-10T01:02:56.918Z {"resultCode":"telINSUF_FEE_P","Fee":"30","LastLedgerSequence":67598284,"Sequence":xxx,"hash":"..."}
2021-11-10T01:03:00.066Z {"resultCode":"telINSUF_FEE_P","Fee":"30","LastLedgerSequence":67598285,"Sequence":xxx,"hash":"..."}
```

If you look at my log, The transactions have the same Sequence (xxx)

And only the last transaction was successful.

Time is not even close. 00:53 ~ 1:03 (during 10 minutes)

I think the transaction fee is too low so all Transaction just in Queue
- so when the average fee was low, the final transaction was Successful 

so My first question is "How to calculate exact FEE, and fast FEE" so my transaction will Success very fast
- and I know I have to change my max FEE conf
- but Is there an average transaction fee site? (like eth gas station) so I can see the right amount of MAX FEE

-----

and I think I can specify a specific sequence. ([sequence filed In the instruction obj](https://xpring-eng.github.io/xrp-api/XRPAPI-data-types-transaction_instructions.html))
- I have to cash my sequence or ask my rippled node ("what is my current sequence in mempool, or something)  

And that's not a good idea, because if the "A transaction" fails, the sequence of other transactions executed after "A transaction" must be corrected.

So what can I do 
I want to know how can I fix this problem 

----

Summary

1. How can I calculate a fast transaction fee
2. Is there an average transaction fee site? (like eth gas station), so I can change my max transaction fee
3. How can I avoid the same sequence (with SDK)

Thank you for your help.

**Comment by mvadari** [comment]
The fee for multisigning is a little different: https://xrpl.org/multi-signing.html

The `prepareTransaction` method will actually calculate the correct fee for you, as long as you have `signersCount` (the number of total signers) in the `instructions` - so you don't need to do it separately yourself.

**Comment by junha-ahn** [comment]
I want to calculate the correct fee. 

"The prepareTransaction method will actually calculate the correct fee for you" 

But I think the `getFee()` function can't calculate the correct fee now. 

Look at the log above the `submit()`  function return to me "telINSUF_FEE_P" 

And There is a same sequence function so I think `prepareTransaction()` is same for `getFee()` function ....

**Comment by junha-ahn** [comment]
sorry, My mistake. 
- "same sequence function" X
- "same sequence transaction" O

Look at my log, there are 8 transactions (log) but the sequence is all same. 
What is the problem now? 

And thank you, "getFee() only returns the fee for a standard transaction, so it won't work for a multisigned transaction."
- So I have to change my fee calculate logic. 

So I have two signatures

so If the "standard fee"(`getFee() result`) is a 1 XRP, I have to set 3 XRP 
- Because "The transaction cost (specified in the Fee field) must be at least (N+1) times the normal transaction cost, where N is the number of signatures provided."
- N(two signatures) + 1 = 3 (`1 XRP * 3 = 3 XRP`)

**Comment by mvadari** [comment]
I would just let `prepareTransaction` calculate the fee for you (which it will do if you leave the `Fee` field blank). It will automatically do the math for you (the normal fee is not 1 XRP, it's ~10 drops of XRP, which is about .00001 XRP). 

The sequence is the same because your transaction failed. The sequence only increments with a successful transaction.

**Comment by junha-ahn** [comment]
Ah, I understand now!!!!

Thank you and I will change my logic

1. I just use `prepareTransaction`
2. And I will set The `MaxFee` field in [instructions](https://xpring-eng.github.io/xrp-api/XRPAPI-data-types-transaction_instructions.html) Because I am afraid that an unexpected amount of fee will be paid.

(My last question) But Is it ok `sign` and `combine` after `prepareTransaction` 

Because I  think, We don't know how many signatures do we need, It just automatically calculate after `combine`?

**Comment by mvadari** [comment]
Re 2: the default `MaxFee` is 2 XRP, so you shouldn't be able to pay more than that. You can set it to a different global value when you initialize the `RippleAPI`. But you can also set a different `MaxFee` for this specific transaction.

You'll need to know the number of signatures at the time of `prepareTransaction`, for the fee calculation. You'll definitely need to know the number of signatures at the time of each `sign`, if you want to re-calculate the fee by hand just before signing. 

If you're referring to the signer quorum, the transaction will fail if you don't have enough signatures. You can also find out what the quorum is with an `account_info` request.

**Comment by junha-ahn** [comment]
Ok Thank you for sharing about default `MaxFee` 

"You'll need to know the number of signatures at the time of prepareTransaction"

I always know the number of signatures in my account

and for calculate  fee, what I need to do in `prepareTransaction()` argument, Do I need to fill the ["Signers" filed](https://xrpl.org/transaction-common-fields.html)? 

Is there a example for multisign transaction with ripplejs?

**Comment by mvadari** [comment]
You can pass a `signersCount` into `prepareTransaction`

The way that multisigning works with the library is that you sign each transaction individually, and then you combine them into one transaction using [`combine`](https://github.com/XRPLF/xrpl.js/blob/1.8.0/docs/index.md#combine). When preparing each individual transaction, put the total number of signers in the [instructions](https://github.com/XRPLF/xrpl.js/blob/1.8.0/docs/index.md#transaction-instructions).

**Comment by junha-ahn** [comment]
Thank you!

```

async function multiSignPayment(paymentObject) {
  const { from, to, amount, tag } = paymentObject

  const multiSignPayment = {
    TransactionType: 'Payment',
    Account: from,
    Destination: to,
    Amount: amount,
    // no Fee filed
  }

  const instructions = {
    maxLedgerVersionOffset: 25,
    signersCount: 2, // Added
  }

  if (tag) multiSignPayment.DestinationTag = Number(tag)

  const prepared = await rippleAPI.prepareTransaction(
    multiSignPayment,
    instructions
  )
  
 // The bottom is all the same.

  const signers = await Secrets.getSigners()
  const signedTransactions = signers.map(({ address, account, secret }) => {
    const addr = address || account
    return rippleAPI.sign(prepared.txJSON, secret, { signAs: addr })
      .signedTransaction
  })
  const combinedTx = rippleAPI.combine(signedTransactions)

 return await rippleAPI.submit(combinedTx.signedTransaction)
}
```
