### ISSUE TITLE
Reference Documentation Gone

### ISSUE THREAD

**Issue by EddieE79** [XRPLF/xrpl.js#1803]
I've noticed since the last release the full reference documentation that used to be at https://js.xrpl.org/ is not available. Is this intentional? Is there an alternative location?

**Comment by natenichols** [comment]
Hi @EddieE79, 

We are moving the code for ripple-binary-codec/ripple-address-codec/ripple-keypairs to be under this library and the XRPLF github.

The docs directory got moved, #1802 fixes it. It should be back up momentarily. Thanks!

**Comment by EddieE79** [comment]
Hi @natenichols,
Thanks for the update, just confirming I can access it again. I appreciate you and your team's work
