### ISSUE TITLE
encode - improve error message when there is a typo in the TransactionType @ripple-binary-codec

### ISSUE THREAD

**Issue by khancode** [XRPLF/xrpl.js#1808]
When trying to [sign](https://xrpl.org/send-xrp.html#4-sign-the-transaction-instructions) a transaction, if the TransactionType is invalid, the error message is cryptic and doesn't make it easy for developers to identify what the problem is.

Original issue: https://github.com/ripple/ripple-binary-codec/issues/126

**Comment by sublimator** [comment]
maybe message could included the levenshtein (sic) difference two

**Comment by JST5000** [comment]
This appears to be resolved (Although it doesn't include the levenshtein difference)
