### ISSUE TITLE
Overload the sign method with another type signature to take and return bytes @ripple-keypairs

### ISSUE THREAD

**Issue by khancode** [XRPLF/xrpl.js#1816]
Title says it all.

Original issue: https://github.com/ripple/ripple-keypairs/issues/103

**Comment by JST5000** [comment]
I don't think this is something we plan on doing, so I'll close the issue for now. (Feel free to re-open if it's important to your workflow)

**Comment by ckniffen** [comment]
I believe this feature was recently re requested on discord.
