### ISSUE TITLE
Feature: sign with bitcoin key (bip39 or bip32) @ripple-keypairs

### ISSUE THREAD

**Issue by khancode** [XRPLF/xrpl.js#1821]
Enable a user to sign using bip39/bip44 or bip32 derived keys, including multisig use cases.

Original issue: https://github.com/ripple/ripple-keypairs/issues/357

**Comment by JST5000** [comment]
Given the workaround of using https://www.npmjs.com/package/ripple-sign-keypairs to sign with bip39 or bip32, I don't think this is an urgent need to be added to the client library. Closing for now.

**Comment by ckniffen** [comment]
Does this work around still work with xrpl.js 3.0?
