### ISSUE TITLE
Remove the develop branch and just use a single `main` branch @xrpl.js

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl.js#1824]
With the recent change to a mono-repo structure, having both a `develop` branch and a `master` branch is awkward. The reason to have both is that `master` is supposed to reflect the last release, while `develop` reflects the current state of development efforts. With a mono-repo though, since development may happen across multiple packages simultaneously, merging develop into master may NOT reflect the latest releases. 

Ex. I might update `xrpl` with a small change, then write a patch for `ripple-address-codec` which I want to release. Master would then have both of these changes, even though I only released `ripple-address-codec`. 

So, we should probably remove develop, and just work directly with `master` since we're not really getting the benefits of a separate 'release' branch. 

Additionally, since we're changing the branch convention anyway, we may as well adopt the new default of calling `master` "`main`". 

One implication of this will be that people with existing PR's will likely have to change the target of their PR to point at `main` instead of `develop`, but that shouldn't be very hard.

**Comment by intelliot** [comment]
Let's do this together next Monday
