### ISSUE TITLE
'Account' does not exist in type 'SignerEntry'

### ISSUE THREAD

**Issue by mrosendin** [XRPLF/xrpl.js#1843]
I'm getting this TypeScript error on v2.0.2.

<kbd>![Screen Shot 2021-12-01 at 10 27 10 AM](https://user-images.githubusercontent.com/3401412/144292217-7aa9daec-0b66-4154-93c5-6f6fee16e3d6.png)</kbd>

[SignerEntry interface](https://github.com/XRPLF/xrpl.js/blob/fcf448da8d18479338d0e39a0bff2c48e3cc49d3/packages/xrpl/src/models/common/index.ts#L62)

**Reproducible code:**

```javascript
import xrpl, { SignerListSet, TxResponse } from "xrpl"

const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233')

/**
 * @function createSignersList
 * Setup the signers list
 */
export async function createSignersList(): Promise<TxResponse> {
  console.log("Creating signers list.")
  const address = await getAddress()
  const { wallet } = await client.fundWallet()
  const tx: SignerListSet = {
    TransactionType: "SignerListSet",
    Account: address,
    SignerEntries: [
      {
        Account: address,
        SignerWeight: 1
      }
    ],
    SignerQuorum: 1
  }
  await client.connect()
  return await client.submitAndWait(tx, {
    wallet
  })
}
```

**Comment by JST5000** [comment]
`SignerEntry` is a weird object because it has a single-field named SignerEntry, which then has data. So, your code should actually look like:
```
SignerEntries: [
   {
       **SignerEntry: {**
            Account: address,
            SignerWeight: 1
        **}**
   }
```

**Comment by JST5000** [comment]
Here's the type definition for it: https://github.com/XRPLF/xrpl.js/blob/3e7a722a4cbdb53d1e219fa62fc778147a098390/packages/xrpl/src/models/common/index.ts#L62

**Comment by mrosendin** [comment]
Thanks @JST5000! I'd be curious to know if the `SignerEntry` key is intentional. In any case, that solves it.

**Comment by JST5000** [comment]
> Thanks @JST5000! I'd be curious to know if the `SignerEntry` key is intentional. In any case, that solves it.

Yeah, unfortunately it's awkward either way (If you try to pull it out, then you end up with `SignerEntries` becoming `Array<{ SignerEntry: SignerEntry }>` which isn't great either.)
