### ISSUE TITLE
Unable to submit transactions

### ISSUE THREAD

**Issue by EddieE79** [XRPLF/xrpl.js#1850]
As of 5 hours ago, I am unable to submit transactions using submitAndWait (https://js.xrpl.org/classes/Client.html#submitAndWait)

I am trying to submit an 'OfferCreate'
My transaction prior to autofill looks like this:
```
const transaction = {
        TransactionType: "OfferCreate",
        Account: walletDto.address,
        Flags: 2148270080, //Fill or kill
        TakerPays: xrpAmount,
        TakerGets: {
          currency: sellDetails.currency,
          issuer: sellDetails.issuer,
          value: sellAmount,
        },
      };
```

I get the following error:
RippledError: Transaction not found.
 ```
data: {
    error: 'txnNotFound',
    error_code: 29,
    error_message: 'Transaction not found.',
    id: 4,
    request: {
      command: 'tx',
      id: 4,
      transaction: '7060D268A825C52F89A054B264BD1F478043EB74892D2844FD68812E21AB24A1'
    },
    status: 'error',
    type: 'response'
  }
```

I have checked on xrpscan.com and sure enough transaction: '7060D268A825C52F89A054B264BD1F478043EB74892D2844FD68812E21AB24A1'
is not on the ledger so the first submit of submitAndWait hasn't been accepted on the ledger.

I have tried connecting the client using:
wss://xrplcluster.com
wss://s1.ripple.com
wss://s2.ripple.com

Yesterday this code was operating correctly. Does anyone know why it may not be working now?

**Comment by mvadari** [comment]
What result do you get when you use `submit` instead of `submitAndWait`? It might be because the load is higher on the XRP Ledger right now, so if your transaction isn't going through properly it's probably waiting in the transaction queue.

**Comment by EddieE79** [comment]
@mvadari,  thanks for the suggestion, that proved really useful.

My result is listed below. 

The most useful part is the "engine_result" field - "telCAN_NOT_QUEUE_FULL"

I looked this up on [xrp tel-codes](https://xrpl.org/tel-codes.html) page which clarifies things - In my attempts to sort this I've probably tried to queue too many transactions at a time when the ledger is already very busy - As I've never experienced this before it's just a guess - Does that sound plausible?
```
result: {
    accepted: true,
    account_sequence_available: SEQUENCE,
    account_sequence_next: NEXT_SEQUENCE,
    applied: false,
    broadcast: false,
    engine_result: 'telCAN_NOT_QUEUE_FULL',
    engine_result_code: -387,
    engine_result_message: 'Can not queue at this time: queue is full.',
    kept: true,
    open_ledger_cost: '5557',
    queued: false,
    tx_blob: MY_BLOB
    tx_json: {
      Account: 'MY_BLOB',
      Fee: '12',
      Flags: 2148270080,
      LastLedgerSequence: SEQUENCE,
      Sequence: NEXT_SEQUENCE,
      SigningPubKey: 'KEY',
      TakerGets: [Object],
      TakerPays: 'SOME DROPS',
      TransactionType: 'OfferCreate',
      TxnSignature: 'SIG',
      hash: 'HASH'
    },
    validated_ledger_index: LEDGERINDEX
  },
```

**Comment by mvadari** [comment]
This error is occurring because a lot of people are submitting transactions (not just you), and the ledger is under a lot of load in general.

**Comment by intelliot** [comment]
Your transaction is trying to pay a fee of only 12 drops (0.000012 XRP). It's more likely to go through if you specify a higher fee (e.g. 0.01 XRP, which is 10000 drops).

**Comment by EddieE79** [comment]
@intelliot Thanks for that suggestion, I found that increasing the maxFeeXRP amount when instantiating the client allowed the transactions to get through.

Thanks everyone for you info and suggestions. Closing this issue.

**Comment by lijianl** [comment]
> @mvadari, thanks for the suggestion, that proved really useful.
> 
> My result is listed below.
> 
> The most useful part is the "engine_result" field - "telCAN_NOT_QUEUE_FULL"
> 
> I looked this up on [xrp tel-codes](https://xrpl.org/tel-codes.html) page which clarifies things - In my attempts to sort this I've probably tried to queue too many transactions at a time when the ledger is already very busy - As I've never experienced this before it's just a guess - Does that sound plausible?
> 
> ```
> result: {
>     accepted: true,
>     account_sequence_available: SEQUENCE,
>     account_sequence_next: NEXT_SEQUENCE,
>     applied: false,
>     broadcast: false,
>     engine_result: 'telCAN_NOT_QUEUE_FULL',
>     engine_result_code: -387,
>     engine_result_message: 'Can not queue at this time: queue is full.',
>     kept: true,
>     open_ledger_cost: '5557',
>     queued: false,
>     tx_blob: MY_BLOB
>     tx_json: {
>       Account: 'MY_BLOB',
>       Fee: '12',
>       Flags: 2148270080,
>       LastLedgerSequence: SEQUENCE,
>       Sequence: NEXT_SEQUENCE,
>       SigningPubKey: 'KEY',
>       TakerGets: [Object],
>       TakerPays: 'SOME DROPS',
>       TransactionType: 'OfferCreate',
>       TxnSignature: 'SIG',
>       hash: 'HASH'
>     },
>     validated_ledger_index: LEDGERINDEX
>   },
> ```

is xrp a decentralized chain????

**Comment by intelliot** [comment]
No; [read here for more info](https://xrpl.org/faq.html).
