### ISSUE TITLE
`getBalances` not documented on js.xrpl.org

### ISSUE THREAD

**Issue by mrosendin** [XRPLF/xrpl.js#1860]
I had to dig into a merged PR to find a sample code that uses `client.getBalances(account)`, I think it would help to have it on the site though.

**Comment by mvadari** [comment]
https://js.xrpl.org/classes/Client.html#getBalances

**Comment by mrosendin** [comment]
My mistake. I'm still getting comfortable with the Client abstraction. Thank you!

**Comment by mvadari** [comment]
For the record, there's also a search function (it's a tiny magnifying glass on the top right)
