### ISSUE TITLE
Can't find an alternative to getServerInfo() & getAccountInfo() in the docs[Migrating from Ripple-lib]

### ISSUE THREAD

**Issue by BukkyOmo** [XRPLF/xrpl.js#1869]
My team is currently migrating to xrpl.js and there seems to be not much in the docs using the js client. No information about

-  getServerInfo()
- getAccountInfo()

Thanks.

**Comment by BukkyOmo** [comment]
I have found a solution to this.

**Comment by intelliot** [comment]
For the record, I believe the recommended migration is to use `Client.request`: https://js.xrpl.org/classes/Client.html#request

For getServerInfo, use server_info: https://xrpl.org/server_info.html

For getAccountInfo, use account_info: https://xrpl.org/account_info.html
