### ISSUE TITLE
Method to check received token from xrpl from a specific address

### ISSUE THREAD

**Issue by mirabledictu** [XRPLF/xrpl.js#1887]
Hi, not sure if this is the correct place to ask, but is there a method to check total received amount of a specific xrpl token (i.e., SGB, CSC) from one address to another?

Thank you!

**Comment by ocean-drop** [comment]
I have deliberately not taken into account the paginated responses. Please refer to the documentation [account_tx](https://xrpl.org/account_tx.html) for more information on pagination (`marker`)

The code below shows the total amount received in USD from the `rBK3ojqhXQxxiUAJxjaN3qzrvKs59Jh72T` address 
  ``` html
<script type="module">
      import xrpl from 'https://dev.jspm.io/npm:xrpl';

      const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233');
      const account = 'rhmNT2dx81NHou8GYqE5jiAmDcebPe1bp1';
      const anotherAccount = 'rBK3ojqhXQxxiUAJxjaN3qzrvKs59Jh72T';

      await client.connect();

      console.log('wallet balances', account, await client.getBalances(account));

      const {
        result: { transactions },
      } = await client.request({
        command: 'account_tx',
        account,
      });

     //for the demonstration the code is a bit verbose in order to see each step, we could easily group all the filters
      const receivedUSD = transactions
        .map(({ tx }) => tx)
        .filter((tx) => tx.TransactionType === 'Payment')
        .filter(
          (payment) => payment.Account === anotherAccount
        )
        .filter(({ Amount: { currency } }) => currency === 'USD')
        .reduce(
          (previousValue, { Amount: { value: currentValue } }) =>
            previousValue + parseFloat(currentValue),
          0
        );

      console.log(receivedUSD);

      client.disconnect();
</script>
```

**Comment by mirabledictu** [comment]
> I have deliberately not taken into account the paginated responses. Please refer to the documentation [account_tx](https://xrpl.org/account_tx.html) for more information on pagination (`marker`)
> 
> The code below shows the total amount received in USD from the `rBK3ojqhXQxxiUAJxjaN3qzrvKs59Jh72T` address
> 
> ```
> <script type="module">
>     import xrpl from 'https://dev.jspm.io/npm:xrpl';
> 
>     const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233');
>     const account = 'rhmNT2dx81NHou8GYqE5jiAmDcebPe1bp1';
>     const anotherAccount = 'rBK3ojqhXQxxiUAJxjaN3qzrvKs59Jh72T';
> 
>     await client.connect();
> 
>     console.log('wallet balances', account, await client.getBalances(account));
> 
>     const {
>       result: { transactions },
>     } = await client.request({
>       command: 'account_tx',
>       account,
>     });
> 
>    //for the demonstration the code is a bit verbose in order to see each step, we could easily group all the filters
>     const receivedUSD = transactions
>       .map(({ tx }) => tx)
>       .filter((tx) => tx.TransactionType === 'Payment')
>       .filter(
>         (payment) => payment.Account === anotherAccount
>       )
>       .filter(({ Amount: { currency } }) => currency === 'USD')
>       .reduce(
>         (previousValue, { Amount: { value: currentValue } }) =>
>           previousValue + parseFloat(currentValue),
>         0
>       );
> 
>     console.log(receivedUSD);
> 
>     client.disconnect();
> </script>
> ```

This is working perfectly. Just some TypeScript issues in `Amount` field. Thanks!
