### ISSUE TITLE
Clarification: Account Object Filter Types

### ISSUE THREAD

**Issue by interc0der** [XRPLF/xrpl.js#1902]
In the official reference documentation, the AccountsObjectsRequest reference defines available account_object filters for the request. The available filters are explicitly listed and are in capitalization<sup>[1]</sup> case type.

>The valid types are: Check , DepositPreauth, Escrow, Offer, PayChannel, SignerList, Ticket, and RippleState (trust line).

https://js.xrpl.org/interfaces/AccountObjectsRequest.html#type

However, the available filters are in lowercase<sup>[1]</sup> case type and underscore formatting.
Additionally, there is a discrepancy in the available types. 

Missing Types : DepositPreauth, PayChannel, Ticket, RippleState, NFT?

https://github.com/XRPLF/xrpl.js/blob/46a8adcac9febf08755c7f74bc244a7123170996/packages/xrpl/src/models/common/index.ts#L3-L9

### Possible Solutions

1. Update documentation to reflect the currently available filters 
2. Update `AccountObjectType` type with missing filters and reformat to match reference documentation.

[1] Case types - https://en.wikipedia.org/wiki/Letter_case

**Comment by mvadari** [comment]
According to the documentation [here](https://xrpl.org/account_objects.html#request-format), it should all be lower-case. 

And yes, it does look like we're missing a few of the types. Thanks for the catch!

**Comment by khancode** [comment]
@interc0der The missing types have been added to AccountObjectType and released in v2.2.2
