### ISSUE TITLE
Binary decode transactions with "unsafe" currency codes

### ISSUE THREAD

**Issue by Silkjaer** [XRPLF/xrpl.js#1919]
Decoding certain objects with "unsafe" currency codes returns an error.

One example is transaction `64CE88666FB8C22BF0025C6E78E41B9E8A6F8D469C2A7101152C919CC3A91118` that is a TrustSet for a currency code `0000000000000000000000005852500000000000`.

Since the currency code decodes to "XRP", the binary decoder fails with "Disallowed currency code: to indicate the currency XRP you must use 20 bytes of 0s".

This makes it impossible to decode historical data from rippled using ripple-binary-codec.

This seem to be introduced after 1.1.3, possibly with #1786.

**Comment by mvadari** [comment]
Relevant commit: https://github.com/ripple/ripple-binary-codec/pull/137
