### ISSUE TITLE
ValidationError: Serialized transaction does not match original txJSON. during CancelOffer

### ISSUE THREAD

**Issue by RishanR** [XRPLF/xrpl.js#1936]
When attempting to cancel an existing offer, I get the following error:

ValidationError: Serialized transaction does not match original txJSON. See error.data
...
data: {
    decoded: {
      TransactionType: 'NFTokenCancelOffer',
      Flags: 0,
      Sequence: 1128610,
      LastLedgerSequence: 1188916,
      Fee: '12',
      Account: 'MY_ACCOUNT_ADDRESS'
    },
    tx: {
      TransactionType: 'NFTokenCancelOffer',
      Account: 'MY_ACCOUNT_ADDRESS',
      TokenIDs: [Array],
      Flags: 0,
      Sequence: 1128610,
      Fee: '12',
      LastLedgerSequence: 1188916
   }
    
I tested offer cancellation on the HTML NFT Token Tester on xrpl 2.1.1 and it also returns this error. However, when using xrpl 2.1.0-beta.1 on the HTML NFT Token Tester, the error is not present.

Based on this, I tried to downgrade my npm package to xrpl@2.1.0-beta.1, but this still returned the same error for me with node.js.

**Comment by adshayanB** [comment]
@RishanR I get the same error as well, my code is really similar to the documentation as well.

**Comment by khancode** [comment]
@RishanR  The [NFT documentation](https://xrpl.org/nftoken-tester-tutorial.html#the-canceloffer-function) and NFToken Tester are incorrect when constructing the `NFTokenCancelOffer` transaction object. The correct property name should be `TokenOffers` rather than `TokenIDs`.

Try this instead:
```
const tokenOfferID = offerTokenId.value
const tokenOffers = [tokenOfferID]

const transactionBlob = {
    "TransactionType": "NFTokenCancelOffer",
    "Account": wallet.classicAddress,
    "TokenOffers": tokenOffers
}
```

**Comment by RishanR** [comment]
> @RishanR @adshayanB The [NFT documentation](https://xrpl.org/nftoken-tester-tutorial.html#the-canceloffer-function) and [NFToken Tester](https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/_code-samples/nftoken-tester/js/nftoken-tester.html#L220) are incorrect when constructing the `NFTokenCancelOffer` transaction object. The correct property name should be `TokenOffers` rather than `TokenIDs`.
> 
> Try this instead:
> 
> ```js
> const tokenOfferID = offerTokenId.value
> const tokenOffers = [tokenOfferID]
> 
> const transactionBlob = {
>     "TransactionType": "NFTokenCancelOffer",
>     "Account": wallet.classicAddress,
>     "TokenOffers": tokenOffers
> }
> ```

This worked perfectly! Thank you very much!

**Comment by khancode** [comment]
No problem! Sorry about the invalid code snippet. We'll merge the fix soon. 😀
