### ISSUE TITLE
NFT token on nft-devnet.xrpl.org not visible

### ISSUE THREAD

**Issue by andrew-keig-noumena** [XRPLF/xrpl.js#1944]
Not sure where to leave this issue, apologies if its in the wrong place:

When viewing my transaction on nft-devnet.xrpl.org, I am not able to see the complete IPFS link.  Also would it be possible to provide a link to IPFS from here.

Example below:

https://nft-devnet.xrpl.org/transactions/DB45197C3165450FC3A1035C5517E09D0724DC9CF461E18899D2D883AC6FD227

**Comment by mvadari** [comment]
The correct repo is https://github.com/ripple/explorer/
