### ISSUE TITLE
ripple-binary-codec not up to date with XLS20 field/name changes

### ISSUE THREAD

**Issue by WietseWind** [XRPLF/xrpl.js#1965]
Changes to XLS20 (NFT amendment, for the sake of consistency) were proposed:
https://github.com/XRPLF/XRPL-Standards/discussions/46#discussioncomment-2473748

These changes have been added to the rippled 1.9.0. This version features the name changes proposed ^^:
https://github.com/ripple/rippled/commit/70779f6850b5f33cdbb9cf4129bc1c259af0013e

Apparently rippled 1.9.0 has already been installed on the XLS-20 devnet:

```
 ✘ wrw@MalusDomestica  /wscat -c wss://xls20-sandbox.rippletest.net:51233
> {"command":"server_info"}
< {
  "result": {
    "info": {
      "build_version": "1.9.0",
      "complete_ledgers": "572-1274828",
```

### The changes have not been applied top `ripple-binary-codec`

As a result no one can interact (sign, submit) properly anymore.

**Comment by khancode** [comment]
XLS20 field rename changes have been deployed for `xrpl.js` and `ripple-binary-codec`.

**Comment by WietseWind** [comment]
Thank you @khancode 

FYI @N3TC4T
