### ISSUE TITLE
Transaction event triggers multiple times

### ISSUE THREAD

**Issue by w3villa-bedprakash** [XRPLF/xrpl.js#1967]
Hi, I'm using `RippleAPI` 
The following `transaction` event emitting multiple times for a single transaction
condition: this issue comes only after the reconnection
```
api.connection.on('transaction', (transactionData) => {
    console.log(transactionData);
 });
```

**Comment by ckniffen** [comment]
@w3villa-bedprakash  My first guess is the code you shared is inside of a callback for when the connection is made. Do you have any more code to share to provide more context?

Additionally you seem to be using the old version of the library have you tried using 2.x?

**Comment by w3villa-bedprakash** [comment]
I have written this code only to elaborate issue
In this program first 60 second transaction event triggers only once for each transaction but after 60 second transaction event triggers 2 times for every transaction.

`const xrpl = require("xrpl");
const hotwalletAddresses = ['rJdafLdhkGAgASnPqBKPJKUPNii9ZY3hvd']
const client = new xrpl.Client("wss://s.altnet.rippletest.net:51233");

client.on('disconnected', (code) => {
    console.log('🔴🔌disconnect event triggered, code:', code);
});

client.on('error', (errorCode, errorMessage) => {
    console.log('🔴Error event triggered ', errorCode + ': ' + errorMessage);
});

client.on('connected', async () => {
    console.log('🔌✅connect event triggered');
    client.connection.on('transaction', (transactionData) => {
        console.log('\n📜Transaction\n', transactionData);
    });
    return client.connection.request({
        command: 'subscribe',
        accounts: hotwalletAddresses,
    });
});


client.connect().then(() => {
    console.log('Ripple server connected to: ');
}).catch((error) => {
    console.log('🔴 ERROR: Ripple server connection error!!\n\n', error);
    client.disconnect();
});



//This code segment only for create test scenario
setTimeout(async () => {
   await client.disconnect();
  await client.connect();
},1000*60);`


 I'm doing this only to test a scenario -> what will happen if anyhow socket will disconnect and we will reconnect it.

**Comment by ckniffen** [comment]
Try moving the following out of `client.on('connected', async () => {`
```
client.connection.on('transaction', (transactionData) => {
   console.log('\n📜Transaction\n', transactionData);
});
```
I believe the way you have it is causing the listener to be registered every time the client is connected.  If you make it disconnect a second time you will likely see the callback fire three times as it stands.

**Comment by mvadari** [comment]
In addition, you shouldn't be using `client.connection` at all - everything should be on the client itself.

**Comment by w3villa-bedprakash** [comment]
Thanks, issue resolved
