### ISSUE TITLE
How to get owner of NFToken?

### ISSUE THREAD

**Issue by Satosh-J** [XRPLF/xrpl.js#2003]
Hello.
I'm making buy offer in xrp20d.
This requires txBlob like this.
```
const transactionBlob = {
        "TransactionType": "NFTokenCreateOffer",
        "Account": wallet.classicAddress,
        "Owner": owner,
        "NFTokenID": nftokenId,
        "Amount": 2000
        "Flags": 2
  }
```
For this, I should know the current owner of NFToken.
How can I get _owner account address_ from _NFTokenID_?
Or is there any other way to make buy offer without knowing owner?

**Comment by JST5000** [comment]
Hey Satosh-J, currently there's no way within XLS-20d to determine the owner from the NFTokenID directly. 

One way that's being resolved is with CLIO (a companion to validators that can offer additional requests) - See this comment in response to a similar question on the spec itself: https://github.com/XRPLF/XRPL-Standards/discussions/46#discussioncomment-2548482

Alternatively, you can use the NFTokenID to get the issuer of the token, then trace back the transactions which involve that token until you find the eventual owner. 

The steps for that would be:
1. Decode an NFTokenID to get the issuer
2. Send an `account_tx` request for that issuer until you find the transaction that trades the NFToken (https://xrpl.org/account_tx.html)
3. Repeat step 2 on each account until you find the eventual owner. (No transactions trading the NFToken between the ledger that account bought the token on, and the current ledger)

The CLIO option will eventually be a very easy-to-use answer to this question, but unfortunately for now it's not quite ready.

**Comment by Satosh-J** [comment]
Thanks you very much.
