### ISSUE TITLE
xrpl.Wallet.generate throws `Not Implemented Yet' error

### ISSUE THREAD

**Issue by barmola** [XRPLF/xrpl.js#2045]
Hi
`xrpl.Wallet.generate` this function is throwing this error  `Not Implemented Yet'

**Comment by JST5000** [comment]
@barmola Could you share what version of xrpl.js you are using? (And a code snippet that reproduces the issue?)

I'm not able to see that issue locally.

**Comment by JST5000** [comment]
Closing as inactive - feel free to reopen if you have a bit of code that reproduces the issue for you.
