### ISSUE TITLE
Need help on migrating from old "ripple-lib" to new ""xrpl".

### ISSUE THREAD

**Issue by code-brewer** [XRPLF/xrpl.js#2047]
I maintain a one-year-old project that use old packages:

```json
    "ripple-address-codec": "^4.1.2",
    "ripple-binary-codec": "^1.1.0",
    "ripple-keypairs": "^1.0.2",
    "ripple-lib": "^1.9.0",
```

Here are the APIs that get block data:

```js
const api = new RippleAPI({...})
	...
let blockNumber = await api.getLedgerVersion(); // get latest block number
api.getLedger({includeAllData:true, includeTransactions: true, ledgerVersion: blockNumber}
```

and also other APIs that used :

```js
api.prepareTransaction
api.preparePayment
api.convertStringToHex
api.xrpToDrops
api.getFee
```

Now, I need to add Token support, but find the new XRP js library "xrpl" have change greatly.  

I am struggle to refactor those code, hoping to find an approach with minimum code reconstruction.

Is there API migrate document to referred to?

Any help will be appreciated!

**Comment by intelliot** [comment]
There's also a migration guide here: https://xrpl.org/xrpljs2-migration-guide.html

**Comment by code-brewer** [comment]
> There's also a migration guide here: https://xrpl.org/xrpljs2-migration-guide.html

Thanks. I also found it by run `yarn install` on old project and get this migrate info from `node_modules/ripple-lib/package.json` file

**Comment by code-brewer** [comment]
> I'm not sure if there is any migration documentation but those functions all exist...
> 
> Prepare Transaction & Prepare Payment are still on the client:
> 
> https://github.com/XRPLF/xrpl.js/blob/main/packages/xrpl/src/client/index.ts
> 
> So use like;
> 
> `client.prepareTransaction()`
> 
> Convert String to Hex & Xrp to Drops are imported like so.
> 
> `import { convertStringToHex, xrpToDrops } from 'xrpl';`

Thanks for your info. I will look into it.

**Comment by khancode** [comment]
@code-brewer Feel free to reopen this if you need any further help.
