### ISSUE TITLE
Destination Tag Range

### ISSUE THREAD

**Issue by sera-korbit** [XRPLF/xrpl.js#2051]
I insert some random number in Destination Tag.
And I got range error as I put number like'9999999999'.
Does XRP Ledger have specific Destination Tag range?

**Comment by intelliot** [comment]
[Destination Tags](https://xrpl.org/source-and-destination-tags.html) are 32-bit unsigned integers (`UInt32`), so they have a range of 0 to 4294967295 (`2^32-1`). `9999999999` is much larger than `2^32-1`, so it cannot be used as a destination tag.
