### ISSUE TITLE
Is it possible to send out all token and XRP at one transaction?

### ISSUE THREAD

**Issue by code-brewer** [XRPLF/xrpl.js#2058]
As title stated.

I want to delete account which has many kinds of tokens. But it require to spent out all tokens first. 
(see:  [unable to delete account](https://github.com/XRPLF/xrpl.js/issues/2057)  )

It would be awesome if we can spend out all token and XRP.

**Comment by mvadari** [comment]
Nope, you've got to send a payment transaction for each currency.

**Comment by intelliot** [comment]
@mvadari is correct and I believe that resolves this issue. Thanks for the question.
