### ISSUE TITLE
how to detect if an account has trustline with a token and cancel this trustline ?

### ISSUE THREAD

**Issue by code-brewer** [XRPLF/xrpl.js#2069]

**Comment by code-brewer** [comment]
It would be better to detect if an account had created trustline  before mint a token to this account.
Does anyone know the way to do this?

**Comment by ckniffen** [comment]
@code-brewer Here is an example of how to get all of the trust lines an account has https://github.com/XRPLF/xrpl.js/blob/89b88336108c37de19d9ba4fb43f2f1bd70c6215/packages/xrpl/test/integration/requests/accountLines.ts.

Here is a guide for how to freeze a trust line https://xrpl.org/freeze-a-trust-line.html#4-send-trustset-transaction-to-freeze-the-trust-line

A trust line can also be removed by setting the amount to 0.

**Comment by code-brewer** [comment]
@ckniffen Thanks. I will try now and feedback.

**Comment by code-brewer** [comment]
It works perfectly.
