### ISSUE TITLE
Can't decode a blob

### ISSUE THREAD

**Issue by nicoeni** [XRPLF/xrpl.js#2072]
Hi and thank you for this package.

I try to get informations with a blob string, When I try xrpl.decode(...) on the website https://npm.runkit.com/ I can see those infos, but when I use the same code in my html file, I get nothing.
I did a alert to see what is returned; I got [object object]; if I take the first element of this array, and do an alert, it says undefined.

Could you help me please?

Thank you

Nicolas

**Comment by pdp2121** [comment]
Hi @nicoeni,

Thanks for raising the question. Could you specify which field(s) you were trying to encode/decode?

Phu

**Comment by nicoeni** [comment]
Hi @pdp2121,
I have this blob test file:

var txblob = "59166110372050100000000000000000005198820159164A38BCFB116E1016F93A7321ED2CAAD276E5A91179C30787ECDCC0E5259A2A3E1590CC369C15FD9A83215514C274409A81726ABF6C8F80989C7C3BC250FA98A30AAA4F880E4C9052C05E9D083CAA2482BB183225A3EFE6A91FF7526A2B6D9C0EAD7443041CA9C68C5B90C149EB13008114E7B5F920D46FD69D52F0142145B48B02308DBB69";

and I want to extract the account, so I do

<script src="https://unpkg.com/xrpl@2.3.1/build/xrpl-latest.js"></script>
<script> 
response = xrpl.decode(txblob)
console.log(response)
</script>

but nothing appear in the console
