### ISSUE TITLE
Remove `lodash` from the xrpl package

### ISSUE THREAD

**Issue by develoQ** [XRPLF/xrpl.js#2118]
When connecting to XRPL with Metamask Snap, due to a Hardend Javascript (SES) limitation, xrpl.js cannot be used (resulting in an error).

This is due to the `lodash` package.

After replacing the `lodash` package with `just`, the error no longer occurs, but I am not sure if this package can be included in xrpl.js.

https://github.com/angus-c/just

**Comment by ckniffen** [comment]
@develoQ I am up for removing lodash all together if the methods used can be done in modern js.

**Comment by WietseWind** [comment]
@ckniffen Exactly, most things are very easy with some map/reduce/filter/... these days.

**Comment by mvadari** [comment]
I believe I tried to remove as much lodash as possible, but in some places there were really nice functions like `groupby` and `omitby` that were hard to replace.

**Comment by WietseWind** [comment]
groupby would be very easy with a reduce fn?

Ugly piece of code, idea is clear, reducer could be a more generic fn of course.

```javascript
const people = [
  { name: 'Nienke', gender: 'F' },
  { name: 'Wietse', gender: 'M' },
  { name: 'Arwen', gender: 'F' },
  { name: 'Quinn', gender: 'M' },
]

const sortedPeople = people.reduce((a, b) => {
  if (!a[b.gender]) {
    Object.assign(a, { [b.gender]: [] })
  }
  a[b.gender].push(b)
  return a
}, {})
```

<img width="225" alt="image" src="https://user-images.githubusercontent.com/4756161/198121939-01dbcad6-a1f3-4c1b-8a49-cc1e45f2849a.png">

**Comment by aruns05** [comment]
@develoQ  @intelliot  is it done. I am keen in learning xrp and want to pick this

**Comment by ckniffen** [comment]
@aruns05 when working on this the solution should reduce the webpack bundle size.

**Comment by ckniffen** [comment]
@aruns05 I went ahead and did this as part of our effort to reduce the bundle size of xrpl.js. Let me know if I missed anything in #2378.

There will be more PRs to reduce size in the next few weeks.

**Comment by ckniffen** [comment]
Done as part of 3.0
