### ISSUE TITLE
Validation of transactions

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl.js#2128]
Hey guys, I'm having trouble locating where the validation of a tx is called. The only location I can find is [here](https://github.com/XRPLF/xrpl.js/blob/d0534f6db43f380fb2e51e262dae0815065c7c10/packages/xrpl/src/models/transactions/transaction.ts#L99). This looks like its only for multisign.

Is there another location the validation is being called?

**Comment by mvadari** [comment]
It's not called anywhere, because it's not really necessary for TypeScript users. The function was written for JS users who don't have that compile-time typechecking, so they can at least have runtime type-checking.

**Comment by dangell7** [comment]
> The validations do more complex validations than just types. I think a few check value ranges.

Agree I think they are valuable.

**Comment by mvadari** [comment]
> The validations do more complex validations than just types. I think a few check value ranges.

Yes, but the intent was for JS users.
