### ISSUE TITLE
Missing fields in `AccountRoot`

### ISSUE THREAD

**Issue by develoQ** [XRPLF/xrpl.js#2144]
The following fields are missing from the `AccountRoot` object

- MintedNFTokens
- urlgravatar

Example of response of result.account_data of `account_info` command
```js
{
  Account: 'rQQQrUdN1cLdNmxH4dHfKgmX5P4kf3ZrM',
  Balance: '111653616',
  Domain: '746571752E646576',
  EmailHash: 'DCA87D72C399A1993247F6BE6E3C929E',
  Flags: 0,
  LedgerEntryType: 'AccountRoot',
  MintedNFTokens: 1,
  OwnerCount: 14,
  PreviousTxnID: 'DA8D4371C70EF552228C5B2D4C113D5379B5F8BDB7E1F5303CEB26CB70175836',
  PreviousTxnLgrSeq: 75818062,
  RegularKey: 'rQQriCKWphqPE7K7VXddtsPHCbEEmbPye',
  Sequence: 61531554,
  index: '6A6192D86708D68A1678859E30F945F3179F55838CB9E56935F618FF103FF113',
  urlgravatar: 'http://www.gravatar.com/avatar/dca87d72c399a1993247f6be6e3c929e'
}
```

**Comment by mvadari** [comment]
Confirmed that this is indeed the case: https://xrpl.org/websocket-api-tool.html?server=wss%3A%2F%2Fs1.ripple.com%2F&req=%7B%22id%22%3A2%2C%22command%22%3A%22account_info%22%2C%22account%22%3A%22rQQQrUdN1cLdNmxH4dHfKgmX5P4kf3ZrM%22%7D

**Comment by mDuo13** [comment]
`urlgravatar` is not a proper field of AccountRoot but is added by the account_info method. It's also not documented.

There is a task [to remove it](https://github.com/XRPLF/rippled/issues/3794) so I recommend not adding it to the xrpl.js model.

Should definitely add `MintedNFTokens` though. Maybe double-check that `NFTokenMinter` and `BurnedNFTokens` (the other fields added by XLS-20) are supported too?
