### ISSUE TITLE
Get NFTokenID from MetaData on Mint

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl.js#2179]
Opening as a follow up to this comment in the Discord: https://discord.com/channels/886050993802985492/886053111179915295/1060468791642955847

Currently we have a way to get the NFTokenID from input parameters (`parseNFTokenID`) but it'd be nice to just be able to get the metadata from a successful NFTokenMint transaction as nixer described. (E.g. `getMintedNFTokenID(metadata:TransactionMetadata)`)

It being one parameter, and being what the ledger actually confirmed is nice.

**Comment by develoQ** [comment]
This Issue can be Closed as the following PR has been merged.

- #2205

**Comment by ckniffen** [comment]
Fixed by #2205
