### ISSUE TITLE
NFTokenMint transaction does not support empty string in URI

### ISSUE THREAD

**Issue by crtag** [XRPLF/xrpl.js#2212]
**Network: wss://s.altnet.rippletest.net:51233**

The following transaction body
```
{
        "TransactionType": 'NFTokenMint',
        "Account": wallet.classicAddress,
        "URI": xrpl.convertStringToHex(''),
        "Flags": 8,
        "TransferFee": 0,
        "NFTokenTaxon": 0 
}
```

causes the following error stack:
```
XrplError: The latest ledger sequence XXXXX is greater than the transaction's LastLedgerSequence (YYYYYY).
Preliminary result: temMALFORMED
    at \xrpl\node_modules\xrpl\dist\npm\sugar\submit.js:65:19
    at Generator.next (<anonymous>)
    at fulfilled (\xrpl\node_modules\xrpl\dist\npm\sugar\submit.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: undefined
}
```

Sample code:
```
const xrpl = require('xrpl');

const net = 'wss://s.altnet.rippletest.net:51233';
const opSeed = '';

const wallet = xrpl.Wallet.fromSeed(opSeed);
const client = new xrpl.Client(net);

client.connect().then(() => {
    console.log(`Connected to ${net}`)
    console.log(`Using address ${wallet.classicAddress}`)
    const transactionBlob = {
        "TransactionType": 'NFTokenMint',
        "Account": wallet.classicAddress,
        "URI": xrpl.convertStringToHex(''),
        "Flags": 8,
        "TransferFee": 0,
        "NFTokenTaxon": 0 
    };
      
    client.submitAndWait(transactionBlob, {wallet})
    .then(tx => console.log(tx))
    .catch(err => console.error(err))
    .finally(() => client.disconnect());

});
```

**Comment by JST5000** [comment]
Thanks for sharing this, I was able to reproduce it locally. (It also seems that even `NFT: undefined` isn't allowed because it doesn't encode/decode to the same thing.) 

My initial impression would be that the client library should interpret an empty string URI as the same as the NFT not including the URI field at all. 

I believe rippled probably doesn't accept empty URI because it's a waste of space. (It's allocating space for a URI, but then not using it to store anything).

**Comment by crtag** [comment]
> I believe rippled probably doesn't accept empty URI because it's a waste of space. (It's allocating space for a URI, but then not using it to store anything).

This behaviour is actually documented as a "favourable" approach to NFT on xrpl to save space. 

So what you can confirm is it's a rippled behaviour rather than SKD? I came across this by accident, and it doesn't block anything, thought that would be the case for some who'd build entirely off-chain storage.

**Comment by JST5000** [comment]
I think this is expected rippled behavior, but the client libraries could deal with it by just removing the URI field if the given string is empty/undefined. Seems like a small change, but I'm not exactly sure where the changes would go in the library.

**Comment by crtag** [comment]
I will see if I can create a pull request for that.

**Comment by crtag** [comment]
OK, so basically it's not about removing a URI field from the transaction as far as I can see the logic through the codebase. It's rather throwing when it's empty so it doesn't confuse rippled.
The right way to fix it is to add another condition in `src\models\transactions\NFTokenMint.ts` to throw when it's an empty string.
Just tested the transaction w/o the URI field and it goes through.
Testing with an `undefined` value causes it to throw **ValidationError: Serialized transaction does not match original txJSON. See error.data** which is misleading too, but at least handled.

Suggestion:

1. Add validation/test for empty string in URI field in `ValidationError: Serialized transaction does not match original txJSON. See error.data` and add respective tests
2. Let `undefined` value in as it's sort of handled.

**Comment by JST5000** [comment]
There will probably be two spots in the code which need changing:
1. In `getSignedTx` to convert `URI: ''` or `URI: undefined` -> removing the URI field from the Transaction being encoded into binary format. ([Link to the function](https://github.com/XRPLF/xrpl.js/blob/fde954640f6f71c53b30a2883cf608b51c526048/packages/xrpl/src/sugar/submit.ts#L189))
2. In `checkTxSerialization` to ensure we view a submitted transaction with `URI: ''` or `URI: undefined` as equal as the decoded transaction, which will have no URI field at all. This function is what throws if you seem to be submitting a transaction you didn't intend to. ([Link to the function](https://github.com/XRPLF/xrpl.js/blob/fde954640f6f71c53b30a2883cf608b51c526048/packages/xrpl/src/Wallet/index.ts#L405))

**Comment by crtag** [comment]
@JST5000 we sort of in disagreement on #1? Agree on #2, though from a developer perspective why would you let `undefined` through? Bad practice.

**Comment by JST5000** [comment]
That's fair. My thought was that the expected behavior for passing in an empty string as a developer would be that it creates an NFToken with no URI. Throwing an error instead just to be up-front about how it'll be represented on ledger seems cleaner to me :) (It just wasn't the way I thought to solve it initially)

As for accepting `URI: undefined` as equal to no `URI` field at all - sometimes it's quite awkward to skip a field when defining your transaction. Whereas it can be convenient to use `undefined` instead of splitting up your initialization into two pieces. 

Ex in the code you shared to begin with: 
```
const tx = {
TransactionType: "NFTokenMint",
URI: xrpl.convertStringToHex('') ?? undefined,
...
}

vs

const tx = {
TransactionType: "NFTokenMint",
...
}
const uri = xrpl.convertStringToHex('')
if(uri) {
  tx.URI = uri
}
```

(I personally feel the 1st version is cleaner to read/write)

**Comment by crtag** [comment]
Yep, that undefined needs to be handled, as it's a valid way to drop the property off the object in JS.

**Comment by mvadari** [comment]
(It also seems that even `NFT: undefined` isn't allowed because it doesn't encode/decode to the same thing.)

This is a library issue, not a rippled issue. 

Does `null` work?

**Comment by crtag** [comment]
I will come back to this and PR over the weekend, some decisions were a bit premature I suppose. Need to check `null` behaviour and understand the code architecture. I feel there are some props in the wrong places which confused me as well.

**Comment by crtag** [comment]
@mvadari @JST5000 
A few more notes and I'm looking for some suggestions to get it sorted.

- `null` value causes the codec to throw __Cannot construct Blob from value given__. Has to get handled properly.
- `validate` is invoked only in `multisign`, and this is quite confusing as `validateNFTokenMint` is invoked there. Is it meant to get called on tx blob explicitly before submitting a transaction? Empty string validation happens in `validateNFTokenMint` though.
- tx can be stripped of undefined & null in `getSignedTx` and that's all

Will sort out the code once above items are clarified

**Comment by mvadari** [comment]
> @mvadari @JST5000 A few more notes and I'm looking for some suggestions to get it sorted.
> 
> * `null` value causes the codec to throw **Cannot construct Blob from value given**. Has to get handled properly.

Hmm, perhaps the codec should strip those out automatically. That will require some more thought, though. For now, this will be resolved if the tx is stripped of undefined and null values prior to reaching the codec.

> * `validate` is invoked only in `multisign`, and this is quite confusing as `validateNFTokenMint` is invoked there. Is it meant to get called on tx blob explicitly before submitting a transaction? Empty string validation happens in `validateNFTokenMint` though.

I think it'll be fine if it's called in `sign` as well.

> * tx can be stripped of any `undefined` & `null` in `getSignedTx` regardless of what transaction is?

Yes. `null` is a superset of `undefined`, so it'll be easier if you just use `null`.

> Will sort out the code once above items are clarified

**Comment by crtag** [comment]
I've updated the pull request, however, since the `validate` has never been running before, the logic to compare encoded&decoded tx vs the original would never work due to the `toUpperCase()` transformation. Hence a shortcut in lines 213-219 of the `packages/xrpl/src/models/transactions/transaction.ts` which I don't quite like. Open to suggestions.

**Comment by JST5000** [comment]
> @mvadari @JST5000 I've updated the pull request, however, since the `validate` has never been running before, the logic to compare encoded&decoded tx vs the original would never work due to the `toUpperCase()` transformation. Hence a shortcut in lines 213-219 of the `packages/xrpl/src/models/transactions/transaction.ts` which I don't quite like. Open to suggestions.

Is the problem that `toUpperCase()` is being called on a null value? I'm not quite sure I understand the issue you're running into. Could you give an example of what happens when you try to do it without the `toUpperCase()` transformation?

**Comment by crtag** [comment]
@JST5000 Nope, this behaviour is irrelevant to NFT stuff under discussion here. `decode(encode(tx))` modifies transaction blob for memos (with `toUpperCase`)  and so on for other properties

**Comment by crtag** [comment]
here's an example of mutation:

original tx:
```
{"TransactionType":"NFTokenMint","Account":"rHLEki8gPUMnF72JnuALvnAMRhRemzhRke","TransferFee":314,"NFTokenTaxon":0,"Flags":8,"Fee":"10","Memos":[{"Memo":{"MemoType":"687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963","MemoData":"72656e74"}}]}
```

decode/encode:
```
{"TransactionType":"NFTokenMint","TransferFee":314,"Flags":8,"NFTokenTaxon":0,"Fee":"10","Account":"rHLEki8gPUMnF72JnuALvnAMRhRemzhRke","Memos":[{"Memo":{"MemoType":"687474703A2F2F6578616D706C652E636F6D2F6D656D6F2F67656E65726963","MemoData":"72656E74"}}]}
```

**Comment by crtag** [comment]
The solution is to:
* Treat empty string `URI` as unacceptable value during _NFTokenMint_ transaction and throw to dev;
* Accept `null` & `undefined` values and drop respective transaction properties from the json blob.

Merged into main.
