### ISSUE TITLE
Support `featureXRPFees` amendment

### ISSUE THREAD

**Issue by ckniffen** [XRPLF/xrpl.js#2219]
This amendment is part of rippled@1.10.0 and updates the fees to be formatted as Amounts.

XRPLF/rippled#4247

- ~~For server_info favor the following in order~~
  - ~~`reserve_base_drops`, `reserve_base`, `reserve_base_xrp`~~
  - ~~`base_fee_drops`, `base_fee`, `base_fee_xrp`~~
  - ~~`reserve_inc_drops`, `reserve_inc_fee`, `reserve_inc_fee_xrp`~~
- ~~If specifically looking for fees such as in the client libraries when autofilling use the command `fee` which is not changed by this PR and is already in drops.~~
- ~~Validations processing will need to be handled similar to `server_info`.~~
- `Fee` property on all transactions remains the same
- `SetFee` transactions
  - `BaseFeeDrops`, `ReserveBaseDrops`, and `ReserveIncrementDrops` will be present when the amendment is passed and on new transactions.  These will be of the type Amount 
  - `BaseFee`, `ReserveBase`, `ReferenceFeeUnits`, `ReserveIncrement` are valid only historically after the amendment passes
  - No need for validation updates in client libraries as this is a pseudo transaction
  - Types should reflect there will be only one of the two sets of fields
- FeeSettings
  - New fields need to be added to the [type](https://github.com/XRPLF/xrpl.js/blob/6fbfab4fa49f9f82e07716609de0d8e30bc5d33d/packages/xrpl/src/models/ledger/FeeSettings.ts#LL9C26-L9C37).

**Comment by sappenin** [comment]
Thanks for reporting this @ckniffen -- @nkramer44 for visibility.
