### ISSUE TITLE
https module issue while importing xrpl 

### ISSUE THREAD

**Issue by rachna-khatnawlia** [XRPLF/xrpl.js#2274]
Hi, i am getting unable to resolve module https error while trying to import xrpl.

![Simulator Screen Shot - iPhone 13 - 2023-04-13 at 12 35 16](https://user-images.githubusercontent.com/60135781/231680679-64f06eca-54a6-408b-8069-10d54d6f8741.png)

**Comment by justinr1234** [comment]
@rachna-khatnawlia please provide more info on your project setup.

Here is common instructions for most setups https://github.com/XRPLF/xrpl.js

You are likely missing a polyfill for your intended environment. This library makes use of NodeJS packages that ship with NodeJS. In a browser environment if you don’t import our prebuilt bundle, you must setup those required packages yourself.

**Comment by justinr1234** [comment]
@rachna-khatnawlia closing for now, please let us know if the above worked
