### ISSUE TITLE
Tests are flakey?

### ISSUE THREAD

**Issue by sublimator** [XRPLF/xrpl.js#2275]
Are the integration tests flakey? 

Suggest:
* Increase Github Actions test runner size (more compute/memory)
* Add a retry mechanism - simply retrying tests a few times, while not ideal, makes the tests much more useful in practice

@mvadari ?

**Comment by justinr1234** [comment]
@sublimator would you be able to link a couple logs or show more specific info?

**Comment by sublimator** [comment]
It's a question.

I thought I noticed a PR build failed different jobs at different times. On
mobile, so I don't have logs.

If they are known flakey(as integration tests can be), I will pay them less
heed.

**Comment by justinr1234** [comment]
Got it, I’m not aware of them being flakey at the moment. The last time they were was when a faucet was going out of commission, but we fixed that.

If you notice any flakey, please drop a line on here.

**Comment by sublimator** [comment]
Will do, thx the info!

**Comment by sublimator** [comment]
Here was where I started wondering: 
https://github.com/XRPLF/xrpl.js/pull/2273#issuecomment-1508297230

**Comment by sublimator** [comment]
[This](https://github.com/XRPLF/xrpl.js/actions/runs/4705546103/jobs/8346162305?pr=2273) looks related to the faucet you mentioned:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/525211/232226567-afee9047-2a26-4cfb-9e97-80dbd8efb6cf.png">

However, in a previous job the "browser" job failed rather than one or more of the "integration" jobs

**Comment by mvadari** [comment]
It's known that the tests are slightly flaky, but they appear to be failing more on your PR. It's almost always because of faucet flakiness/rate limiting.

**Comment by sublimator** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/525211/232638340-a48fc59d-7fb1-43d5-b735-081eb801b3c5.png">

5th time's a charm! 

Can see a few other PRs that seem at a glance to be victims:
- https://github.com/XRPLF/xrpl.js/pull/2226
- https://github.com/XRPLF/xrpl.js/pull/2149

**Comment by sublimator** [comment]
Must have had bad luck before.
Pushes since opening this haven't yielded any issues.
Closing.
