### ISSUE TITLE
Actual value for BookOffer.TakerPays is not the same as the type declaration

### ISSUE THREAD

**Issue by markibanez** [XRPLF/xrpl.js#2279]
We are getting a mismatch in actual value and types. When highlighted, BookOffer.TakerPays is supposedly 
`(property) Offer.TakerPays: Amount`

```typescript
const response = await client.request({
  command: 'book_offers',
  ledger_index: 'validated',
  taker_gets: {
    currency: 'XRP',
  },
  taker_pays: {
    currency: line.currency,
    issuer: line.account,
  },
});

for (const offer of response.result.offers) {
  // this is what the type suggests but breaks in runtime
  const totalTakerPaysTS = Number(order.TakerPays.toString());

  // this works in runtime but we actually have to @ts-ignore 
  const totalTakerPaysActual = Number(order.TakerPays.value);
}
```

**Comment by pdp2121** [comment]
Hi @markibanez, thanks for reaching out about the issue! `Amount` is an object consisting of 3 fields (`value`, `currency`, `issuer`), so you might not be able to cast it to a Number directly. I would suggest you to use the supported `to_JSON()` method and extract the value there. Please see the `Amount` class definition for reference:
https://github.com/XRPLF/xrpl.js/blob/main/packages/ripple-binary-codec/src/types/amount.ts

Please let me know if you have any further questions.

**Comment by ckniffen** [comment]
The Amount type is an object with those 3 fields or it in the case of XRP it is a string of the number of drops.

https://xrpl.org/currency-formats.html#xrp-amounts
https://xrpl.org/currency-formats.html#token-amounts

**Comment by mvadari** [comment]
```ts
interface IssuedCurrency {
  currency: string
  issuer: string
}

export interface IssuedCurrencyAmount extends IssuedCurrency {
  value: string
}

export type Amount = IssuedCurrencyAmount | string
```

**Comment by markibanez** [comment]
Hi @pdp2121 and thanks for your reply. I understand what you are saying and I think you are correct in saying the in runtime, the `TakerPays` property is of type `Amount` which is why it works when we use `TakerPays.value`. Sorry for not being clear but my issue not the ability to cast it to a number. My issue is maintain typesafety in my codebase.

When coding in VS code, intellisense does not pickup on those three fields you mentioned. Instead it only has two methods `toString` and `valueOf`

![image](https://user-images.githubusercontent.com/7534847/234571452-cf7e1b38-d41f-4454-aea5-f31bb1a6325d.png)

If I try to access to fields in code, I get type errors on all three fields
![image](https://user-images.githubusercontent.com/7534847/234572517-0e09c33d-c50a-4134-809f-7e7dc2fd663c.png)
![image](https://user-images.githubusercontent.com/7534847/234572639-8a01c76e-1f7f-4aab-b901-731edabe670c.png)
![image](https://user-images.githubusercontent.com/7534847/234572698-fdb8ac51-c983-4e01-b571-7cea396f6d16.png)

Which then forces us to use @ts-ignore for us to be able to build and deploy which we do not want to do.

**Comment by mvadari** [comment]
You'll need to check whether it's a string first (it'll be a string if it's representing XRP). An assert might be good enough for you.

**Comment by ckniffen** [comment]
More of these types have been exported.
