### ISSUE TITLE
`getBalances` possible bug.

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl.js#2311]
The `client.getBalances` sugar function is failing on "rDPMFNFTsZtZxH86J3TozTXQUYiHGX52RS".

Returns an `invalidParameters` response.

Not sure if this is something I'm doing wrong or just some weird edge case.

**Comment by jonathanlei** [comment]
Same with me - tested with 2.7.0 and it worked for me. Could you post the code you used or update 2.7.0 and try again?

**Comment by dangell7** [comment]
It only occurs on `wss://xrplcluster.com/` now. 

I swear it happened.

**Comment by dangell7** [comment]
@KumarUjjwal2022
