### ISSUE TITLE
Creating a web app that integrates with the ledger wallet

### ISSUE THREAD

**Issue by joedakwa** [XRPLF/xrpl.js#2315]
Hi,

I have been tasked with creating a simple web app that integrates with a ledger wallet.

I will need to create a simple "connect wallet" button on the page which allows user to connect their wallet.

This should display their balance in the UI.

This is the brief:

**Frontend**:
1.1. Develop a simple web application (you can use any front-end web framework like React,
Angular, Vue.js, etc.).
1.2. The application should have a button labelled 'Connect Wallet'.
1.3. Once clicked, the application should prompt the user to input their XRP wallet public key
and sign a message (this could be a simple predefined string). This process will confirm that
the user controls the wallet without revealing the private key.
1.4. After the wallet connection is established, display the wallet's public key and current
balance in the UI.

**Backend**:
2.1. The backend can be implemented in a language of your choice (Node.js, Python, Java,
etc.).
2.2. Create an API endpoint to handle the 'Connect Wallet' request. This endpoint should
take the wallet keys as parameters.
2.3. Use an XRP Ledger library (like Ripple-lib in Node.js) to establish a connection to the
XRP Ledger and retrieve the wallet information.
2.4. The response should indicate whether the connection was successful or not and should
return the wallet's public key and current balance.

Can anyone recommend where i start or point me in the direction of a tutorial anywhere?

Thanks

**Comment by justinr1234** [comment]
Hey @joedakwa I would recommend starting here: https://xrpl.org/xrpl-quickstart.html

Also you don't have to have a backend to do this. It can all live in the frontend using xrpl.js

**Comment by joedakwa** [comment]
> Hey @joedakwa I would recommend starting here: https://xrpl.org/xrpl-quickstart.html
> 
> Also you don't have to have a backend to do this. It can all live in the frontend using xrpl.js

Right, i see. Sorry, i am used to doing all of this on ETH, so new to XRP.

How is this all handled in the frontend via xrpl.js?

**Comment by shadymoses** [comment]
@joedakwa I think this might be what you're looking for: https://learn.xrpl.org/course/code-with-the-xrpl/

**Comment by joedakwa** [comment]
> @joedakwa I think this might be what you're looking for: https://learn.xrpl.org/course/code-with-the-xrpl/

Does this show me how to display a users balance and public key in the UI of the web app?

**Comment by ckniffen** [comment]
@joedakwa Did these resources answer your questions?

**Comment by joedakwa** [comment]
> @joedakwa Did these resources answer your questions?

Hi,

I started looking at this tutorial 

https://xrpl.org/build-a-browser-wallet-in-js.html

Which seems more in line with what i am trying to achieve.

However, i am having problems displaying the wallet information. Its just not responding at all.

I get this error message:

util.js:109 Uncaught ReferenceError: process is not defined

    at node_modules/util/util.js (util.js:109:1)
    at __require (xrpl.js?v=c647c0c4:3:50)
    at node_modules/assert/build/internal/assert/assertion_error.js (assertion_error.js:35:16)
    at __require (xrpl.js?v=c647c0c4:3:50)
    at node_modules/assert/build/assert.js (assert.js:36:22)
    at __require (xrpl.js?v=c647c0c4:3:50)
    at node_modules/xrpl/dist/npm/client/index.js (index.ts:4:1)
    at __require (xrpl.js?v=c647c0c4:3:50)
    at node_modules/xrpl/dist/npm/client/BroadcastClient.js (BroadcastClient.ts:1:1)
    at __require (xrpl.js?v=c647c0c4:3:50)

Any suggestions?

**Comment by JST5000** [comment]
The conversation for this has moved to this thread in xrpl-dev-portal for now - https://github.com/XRPLF/xrpl-dev-portal/issues/1918

**Comment by justinr1234** [comment]
@joedakwa I’m going to close this issue, please let us know if you need more help!

**Comment by joedakwa** [comment]
> @joedakwa I’m going to close this issue, please let us know if you need more help!

Sure will do thanks!
