### ISSUE TITLE
Question about the ledger close time

### ISSUE THREAD

**Issue by 9oelM** [XRPLF/xrpl.js#2348]
So I've been trying to wrap my head around the various sources about the ledger close time (please let me know if this is not the best place to ask. Im asking here because I have been reading the code and found that it has a line that is relevant to the close time).

- [The code says it's 1s](https://github.com/XRPLF/xrpl.js/blob/main/packages/xrpl/src/sugar/submit.ts#L12)
- The [reliable tx submission diagram](https://xrpl.org/img/reliable-tx-submission.svg) shows you need to wait for ~4s for the next validated ledger.
- And finally [the official documentation](https://xrpl.org/ledgers.html#ledger-close-times) seems to say 10 secs?

So I just wanna know which duration of seconds would be the most reliable information to follow.

Cheers.

**Comment by JST5000** [comment]
Hey @9oelM, probably the best place to ask would be in the Developer DIscord, but happy to answer anyway :) 

If you're asking how much time it actually takes for a ledger to close, I would look at one of the explorers. Ex. https://livenet.xrpl.org/ shows that it takes about 3.8 seconds on mainnet. (This varies by network - you can click around to a few others to see how long - but the ~3-4 second ballpark has historically been fairly consistent, but varies ledger to ledger by several milliseconds)
![image](https://github.com/XRPLF/xrpl.js/assets/19694186/6d298d79-b4a7-49d8-82d0-f636e25d978e)

If you're referring to the actual field on ledger objects that says when they closed (`close_time`) then the official docs you pointed to are correct in saying that the time gets rounded to the nearest 10 second interval. If more than one ledger closes in that 10 second interval, they will just increment the `close_time` by 1. So it's close, but not fully accurate to the wall-clock time when a ledger actually closes.
