### ISSUE TITLE
"getTransactions" method on RippleAPI with Clio server

### ISSUE THREAD

**Issue by some-dev** [XRPLF/xrpl.js#2354]
I am encountering an issue while using the getTransactions method on the RippleAPI library in conjunction with a Clio server. The goal is to retrieve transactions for a specific Ripple account. However, the code snippet provided below fails with the following error message:
```
const rippleApi = new RippleAPI({
    server: 'wss://s2.ripple.com'
})

const tx = await rippleApi.getTransactions("rLKKAHHiVoiFGcmaRkxXoD93J84ZUvDh4e",
    {
        minLedgerVersion: 80497237,
        maxLedgerVersion: 80760943,
        earliestFirst: true,
        types: [
            "payment"
        ],
    })
```

fails with
`This is a clio server. clio only serves validated data. If you want to talk to rippled, include \'ledger_index\':\'current\' in your request`

## Issue
The getTransactions method fails to retrieve transactions when using a Clio server, and it requires the inclusion of the 'ledger_index':'current' parameter in the request to interact with the rippled server.

## Expected Behavior
I expect the getTransactions method to work seamlessly with the Clio server and correctly pass the 'ledger_index':'current' parameter in the request to retrieve transactions.

Any guidance on how to modify the code to make the "getTransactions" method work with the Clio server and include the required 'ledger_index':'current' parameter would be greatly appreciated.

**Comment by ckniffen** [comment]
RippleApi is no longer supported please use the latest `xrpl` package.

**Comment by ckniffen** [comment]
@some-dev I found a workaround.  If you request `limit: 100` it will work.

https://replit.com/@ckniffen/UnacceptableFineLogin#index.js

**Comment by some-dev** [comment]
thanks for rapid response, il apply this workaround and will plan migration to the newer api
