### ISSUE TITLE
Legacy BIP39

### ISSUE THREAD

**Issue by kristoffer-paulsson** [XRPLF/xrpl.js#2383]
Hi I have a wallet with XRP and can't access them presumably because of no wallet support. I do have a BIP39 mnemonic which I need, can you supply the old fromMnemonic for legacy reasons?

**Comment by JST5000** [comment]
There is currently a function for that in xrpl.js called `Wallet.fromMnemonic` - https://js.xrpl.org/classes/Wallet.html#fromMnemonic 

Let me know if it doesn't work :)
