### ISSUE TITLE
Replace ripple_path_find with path_find in paths snippet

### ISSUE THREAD

**Issue by justinr1234** [XRPLF/xrpl.js#2385]

**Comment by JST5000** [comment]
Closing since `ripple_path_find` is a fine similar request to send

**Comment by mvadari** [comment]
It is recommended that people use `path_find` instead of `ripple_path_find` especially when you have a WS client (like xrpl.js). IMO this should be reopened, since snippets should be promoting best practices.

**Comment by mvadari** [comment]
> @mvadari Both the commands `path_find` and `ripple_path_find` are supported by JSON-RPC protocol. Why is `path_find` recommended for WebSocket connections ? (apart from having to subscribe to continuous stream of updates)

`path_find` is recommended over `ripple_path_find` because paths change every ledger and `ripple_path_find` only returns the results once.

From the docs for [ripple_path_find](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/path-and-order-book-methods/ripple_path_find):
> However, the results tend to become outdated as time passes. Instead of making multiple calls to stay updated, you should instead use the [path_find method](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/path-and-order-book-methods/path_find/) to subscribe to continued updates where possible.
