### ISSUE TITLE
sometimes the xrpl api request is failed, 

### ISSUE THREAD

**Issue by AtosDev** [XRPLF/xrpl.js#2411]
RippledError: The requested object was not found.
  data: {
    error: 'objectNotFound',
    error_code: 92,
    error_message: 'The requested object was not found.',
    id: 3,
    request: {
      command: 'nft_sell_offers',
      id: 3,
      ledger_index: 'current',
      nft_id: '5555555555555555555555555555555555555555555555555555555555555555'
    },
    status: 'error',
    type: 'response',
    forwarded: true,
    warnings: [
      {
        id: 2001,
        message: "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
      }
    ]
  }
}

**Comment by ckniffen** [comment]
This is the intended response if there are not any sell offers for an nft.  The same applies to buy offers.

See: https://github.com/XRPLF/rippled/issues/4339
