### ISSUE TITLE
Currency symbol length Issue

### ISSUE THREAD

**Issue by sushantamandal** [XRPLF/xrpl.js#2464]
Getting issue in transaction for some currencies whose symbol length is more than three character

**Comment by JST5000** [comment]
Hey @sushantamandal you're probably running into "non-standard currency codes" - https://xrpl.org/currency-formats.html#currency-codes

Basically on the XRPL, currencies can be represented either as a 3 character string, or a 40-byte hex string. This is to make it easy for usual "ticker" codes like USD, while still allowing for more custom naming when desired. 

Although there's no official standard for how the 40 byte strings are encoded, this is the logic livenet.xrpl.org uses to decode those strings: https://github.com/ripple/explorer/blob/0e3af45553aedacb83c6ff732684c1536c0f6a35/src/containers/shared/components/Currency.tsx#L30
