### ISSUE TITLE
version_invalid: version bytes do not match any of the provided version(s)

### ISSUE THREAD

**Issue by Cainuriel** [XRPLF/xrpl.js#2472]
Hi, I am new to XRP.
I have integrated your example script for sending XRP in a dapp made with sveltekit. But I get this error at the point where it needs to be signed. I can't find a place where I can check the errors and I decided to write to you.
I hope this is a correct way to do it.
If not, I apologize.

```javascript
// In browsers, use a <script> tag. In Node.js, uncomment the following line:
import xrpl from 'xrpl';

// Wrap code in an async function so we can use await
export default async function send(seed, amount) {

    // Define the network client
    const client = new xrpl.Client("wss://s.altnet.rippletest.net:51233/")
    await client.connect();


    // sender account
    const wallet = xrpl.Wallet.fromSecret(seed);

    // Prepare transaction -------------------------------------------------------
    const prepared = await client.autofill({
        "TransactionType": "Payment",
        "Account": wallet.address,
        "Amount": xrpl.xrpToDrops(amount),
        "Destination": "sngPYH22VNm9ppD5QmJSnP6zizENF"
    });

    const max_ledger = prepared.LastLedgerSequence
    console.log("Prepared transaction instructions:", prepared)
    console.log("Transaction cost:", xrpl.dropsToXrp(prepared.Fee), "XRP")
    console.log("Transaction expires after ledger:", max_ledger);

    // ERROR IN THIS LINE
    const signed = wallet.sign(prepared)
    console.log("Identifying hash:", signed.hash)
    console.log("Signed blob:", signed.tx_blob)

    // Submit signed blob --------------------------------------------------------
    const tx = await client.submitAndWait(signed.tx_blob);
    console.log(`Submit signed blob transaction`, tx);

    // Check transaction results -------------------------------------------------
    console.log("Transaction result:", tx.result.meta.TransactionResult)
    console.log("Balance changes:", JSON.stringify(xrpl.getBalanceChanges(tx.result.meta), null, 2));



   // Mis propias comprobacoines de saldo -------------------------------------------------
    const walletObjetivo = xrpl.Wallet.fromSecret(seed);

    // Get info from the ledger about the address we just funded
    const responseObjetivo = await client.request({
        "command": "account_info",
        "account": walletObjetivo.address,
        "ledger_index": "validated"
    })

    console.log("Balance de la cuenta destino: ",responseObjetivo.result.account_data.Balance);

    // const responseOrigin = await client.request({
    //     "command": "account_info",
    //     "account": wallet.address,
    //     "ledger_index": "validated"
    // })

    // console.log("Saldo de la cuenta original",responseOrigin.result.account_data.Balance);



    // Disconnect when done (If you omit this, Node.js won't end the process)
    client.disconnect()
  }
  ```
  
![image](https://github.com/XRPLF/xrpl.js/assets/37802572/7f236303-2332-4480-b6ea-3b32affbe22f)

**Comment by JST5000** [comment]
@Cainuriel welcome :) 

The issue seems to be that your `Destination` field in your transaction is a secret `s...` instead of an address `r...`. 
If you do `Wallet.fromSeed("sngPYH22VNm9ppD5QmJSnP6zizENF").address` instead it should work if you only know the secret. Generally though you should be able to find the address for accounts more easily than the secret. 

Let me know if that resolves your issue!

**Comment by Cainuriel** [comment]
> @Cainuriel welcome :)
> 
> The issue seems to be that your `Destination` field in your transaction is a secret `s...` instead of an address `r...`. If you do `Wallet.fromSeed("sngPYH22VNm9ppD5QmJSnP6zizENF").address` instead it should work if you only know the secret. Generally though you should be able to find the address for accounts more easily than the secret.
> 
> Let me know if that resolves your issue!

Oh my god!! its true!!
Thank goodness they are test accounts but what a shame....
Thank you very much for your quick response. The function now works with the extraordinary speed that characterises your network.
Just one more thing...

Can I still use this way to comment on problems in my development?
I promise to check my code better next time... :)

**Comment by JST5000** [comment]
@Cainuriel You're welcome to reach out if you run into things (and we appreciate issues to improve quality of life as well - sometimes errors are needlessly opaque as an example!) 

That being said, you'll likely get a faster response from posting in the [developer discord here](https://xrpldevs.org) as a first go to for questions / confusion :)

**Comment by Cainuriel** [comment]
> @Cainuriel You're welcome to reach out if you run into things (and we appreciate issues to improve quality of life as well - sometimes errors are needlessly opaque as an example!)
> 
> That being said, you'll likely get a faster response from posting in the [developer discord here](https://xrpldevs.org) as a first go to for questions / confusion :)

Fantastic. I finally found your discord. I take note of what you say. 
Thank you very much.
