### ISSUE TITLE
deno unable to find polyfill!cjs 

### ISSUE THREAD

**Issue by diadal** [XRPLF/xrpl.js#2618]
Deno is unable to start 

`import xrpl from 'https://dev.jspm.io/npm:xrpl'`

`Watcher Process started.
error: Module not found "https://dev.jspm.io/npm:object-is@1/polyfill!cjs".
    at https://dev.jspm.io/npm:assert@2!cjs:4:8
Watcher Process failed. Restarting on file change...
`

**Comment by JST5000** [comment]
What version of xrpl.js were you using? 

(We just did a release last week which removes a lot of the polyfills which used to be required for xrpl.js, but we haven't tested with Deno so I'm not sure if it will affect the issue you're encountering)
