### ISSUE TITLE
xrpl.Wallet.fromSeed generates different wallet than it should

### ISSUE THREAD

**Issue by fakirpic** [XRPLF/xrpl.js#2636]
i generate a random wallet at somewhere else than xrpl, trying to import by xrpl, but getting different address
as example for this 
`shTBcvGPVw9tzTZhWpkzBAkiqdFz6`
seed key i get
`rfA77Zy5HT1XKNQDR56xaR8TL7HxzJCYKM` as address at osmwallet,
but at xrpl i get 

![image](https://github.com/XRPLF/xrpl.js/assets/5578194/ad4c7063-4e41-4fdf-868a-05e6ea0d9901)

xrpl.Wallet.fromSeed("shTBcvGPVw9tzTZhWpkzBAkiqdFz6")
`Wallet {
  publicKey: 'EDC675EEC8D183AEE43124882D70B924D3F14131A4F52310A4F95EC8DF92847FA4',
  privateKey: 'ED4C3B490EBF4CDE1624F5A692CA8B48DF3A2A738F1ADF2E5698F090F5F42EE6E7',
  classicAddress: 'rfRp96xJebfYdXdWSmPDEDjXcbYmcodfun',
  seed: 'shTBcvGPVw9tzTZhWpkzBAkiqdFz6'
}`
why,is this a bug or  what may I be doing wrong?

**Comment by JST5000** [comment]
The issue is that by default the Wallet uses an `ED25519` encoding instead of the older but less performant `Secp256k1` encoding. When generating your wallet, please specify `algorithm = ECDSA.secp256k1` (or equivalently: `algorithm = "ecdsa-secp256k1"`)

**Comment by Jonathan-Dobson** [comment]
I think the algorithm information is encoded in the seed and can be extracted with decodeSeed()
We should build a feature into the Wallet.fromSeed() to auto-detect the algorithm.
