### ISSUE TITLE
Provide support for Ownership Proofs

### ISSUE THREAD

**Issue by 0x4Graham** [XRPLF/xrpl.js#2648]
Hi 👋 

Can you please consider providing support for ownership proofs, such as a simple API `signMessage([Your message]). This is a common standard in all other networks and Ripple should consider supporting such functionality.

**Comment by pdp2121** [comment]
Hi @0x4Graham , thanks for raising the issue. Just to be clear, is it the ability to sign arbitrary amount of data and then verify the signer? If so, I will create a ticket and put it into our backlog

**Comment by mvadari** [comment]
`ripple-keypairs` already supports this via the `verify` method.

**Comment by 0x4Graham** [comment]
Do you know if wallets support this API? I.E, Ledger Hardware wallets etc?

**Comment by mvadari** [comment]
You'll have to raise that issue with Ledger.
