### ISSUE TITLE
tfTwoAssetIfEmpty flag is missing

### ISSUE THREAD

**Issue by zgrguric** [XRPLF/xrpl.js#2666]
https://github.com/XRPLF/xrpl.js/blob/b9af7bdb6c6d601356da73f4531a035d56d73767/packages/xrpl/src/models/transactions/AMMDeposit.ts#L18

**Comment by ckeshava** [comment]
hello @zgrguric ,
thank you for bringing this issue to our attention. we are working on fixing it.
