### ISSUE TITLE
'nft_info' method is unknown

### ISSUE THREAD

**Issue by chptlouis** [XRPLF/xrpl.js#2680]
I am currently developing a sort of NFT marketplace on XRPL for a school project.

Basically what I needed today was to retrieve all informations about an NFT thanks to its ID.

Found the NFTInfoRequest Interface in the docs, with the 'nft_info' method, I tried to use it but I get an error telling me that the method is unknown.

Tried other different commands in the same request to be sure my code wasn't the problem here.

![image](https://github.com/XRPLF/xrpl.js/assets/75856785/bd51c24d-1c78-4843-8924-24bf3db601b9)
![Capture d’écran du 2024-04-10 12-47-04](https://github.com/XRPLF/xrpl.js/assets/75856785/5b4556b2-011c-4dfd-9752-60ed77b0c649)

**Comment by ckniffen** [comment]
You are likely pointing at a rippled node.  `nft_info` is only supported on clio nodes.

**Comment by pdp2121** [comment]
I'm closing this one. Please feel free to reopen if the issue persist.
