### ISSUE TITLE
trouble using TransactionType: ClaimReward

### ISSUE THREAD

**Issue by gadget78** [XRPLF/xrpl.js#2746]
im trying to use a TransactionType: of 'ClaimReward', but keep getting... 
```/root/evernode-deploy-monitor/node_modules/xrpl-binary-codec-prerelease/dist/types/st-object.js:117
                throw new TypeError(`Unable to interpret "${field.name}: ${xAddressDecoded[field.name]}".`);
                      ^
TypeError: Unable to interpret "TransactionType: ClaimReward".
```

so i tried using different module, 
`npm install --save @transia/xrpl` and then using `const { Client} = require('@transia/xrpl')`
still had same issues, so i tried adding

`npm install xrpl` and then just using `const { Client} = require('xrpl')`
that gives API version errors  
```
const error = new errors_1.RippledError((_a = errorResponse.error_message) !== null && _a !== void 0 ? _a : errorResponse.error, errorResponse);
                          ^

RippledError: invalid_API_version
```
i get this error even at the client.connect() (can i state a different version at the connect stage?)

what do you think im doing wrong ?

**Comment by dangell7** [comment]
You've now mixed the packages together I'm assuming. Try removing the node_modules and only installing the `@transia/xrpl` library.

**Comment by gadget78** [comment]
Thsnkyou, 
Will give removing and adding just that module. 
And will paste in more error and code if needs be once I'm back home from work...

**Comment by mvadari** [comment]
xrpl.js does not directly support any Xahau transactions. If this is an issue with `@transia/xrpl`, I recommend opening an issue on that repo/fork.
