### ISSUE TITLE
Use `client.connect()`, `client.submitAndWait()`, `client.getLedgerIndex()` etc. with `api_version: 1`

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl.js#2759]
These methods cannot be used with `api_version: 1` because the default value, `api_version: 2`, is used by default and cannot be changed by parameters.

**Comment by tequdev** [comment]
We can specify the default apiVersion by doing the following

```ts
const client = new Client()
client.apiVersion = 1
```

**Comment by khancode** [comment]
@tequdev you can also specify api_version as a parameter within a Request.

**Comment by tequdev** [comment]
parameter `api_version` is not available in `client.connect()`, `client.submitAndWait()`, and `client.getLedgerIndex()`.
