### ISSUE TITLE
Test Fail For Api Version 1

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl.js#2818]
I'm not sure if this was intended but if I change the DEFAULT_API_VERSION to RIPPLED_API_V1 a number of integration tests fail. 

Feel free to close this if that is the intended result.

**Comment by ckeshava** [comment]
Hello @dangell7 , the integration tests are using `rippled` `v2.2.0-b3` build. Yes, if the API version is changed to `1`, that could violate many of the integration tests. 

Unless we execute separate docker containers for every API version upgrade of rippled, I can't think of a trivial way to test all the versions.

**Comment by ckeshava** [comment]
@dangell7  please let me know if you need further clarification.
