### ISSUE TITLE
Plagued by tefBAD_AUTH due to latest ledger sequence

### ISSUE THREAD

**Issue by bc-maker** [XRPLF/xrpl.js#2860]
I've been battling this all day. I cannot submit any transactions - Receiving error: 

Error creating purchase for record: undefined XrplError: The latest ledger sequence x is greater than the transaction's LastLedgerSequence (x).
Preliminary result: tefBAD_AUTH
at ... \node_modules\xrpl\dist\npm\sugar\submit.js:45:19

What is the root cause of this issue? 
I've confirmed that my wallet + keys are signing successfully

**Comment by Kendra6738** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by bc-maker** [comment]
Yeah I'm having issues - Hence the ticket

**Comment by 22JamesDd** [comment]
> Yeah I'm having issues - Hence the ticket

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID Xrp09126 for recovery guidelines.

[XRPLF Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by bc-maker** [comment]
Joined the XRPL discord and found solution straight away. Have to declare the algorithm when signing wallet e.g. 
![image](https://github.com/user-attachments/assets/05c2ded3-c563-4bec-a377-71d11e05dde7)
