### ISSUE TITLE
[enhancement] Autobridged book when IOU:IOU

### ISSUE THREAD

**Issue by tuloski** [XRPLF/xrpl.js#782]
The api.getOrderbook should return the autobridged book when the two legs are two IOUs.

Maybe an option can decide if getting the autobridged or not.

**Comment by pftq** [comment]
I've built this into my own wallet/site here:
https://www.theworldexchange.net/

You can find the code block for it by searching for bridgedbook in the source code.  It would be nice to have it in ripplib to standardize this, but just sharing in case it helps.

**Comment by intelliot** [comment]
Sorry for the long delay in replying, but I like this idea. Would you like to submit a PR?

**Comment by tuloski** [comment]
I worked on that, but on the "parsing" side and it was a nightmare, even because not all the useful information are returned with getOrderbook.
I don't have the skills to work directly on the API. I'm a JS user only because it's the easiest way to interact with rippled :).
